name:                invest
version:             0.1.0.0
github:              "githubuser/invest"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/invest#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cassava
- containers
- Decimal
- exceptions
- record-hasfield
- record-dot-preprocessor
- safe
- string-conversions
- text
- vector

ghc-options:
  - -Wincomplete-patterns
  - -Wdodgy-exports
  - -Wdodgy-imports
  - -Wincomplete-record-updates
  - -Wname-shadowing
  - -F -pgmF=record-dot-preprocessor
  - -fdefer-typed-holes

default-extensions:
  - ApplicativeDo
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances



library:
  source-dirs: src

executables:
  invest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - invest

tests:
  invest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - invest
